services:
  db:
    image: mysql:8.0
    container_name: tp_extra_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tp_extra_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - tp_extra_db_data:/var/lib/mysql

volumes:
  tp_extra_db_data:
  